---
kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: weather-stations
  labels:
    strimzi.io/cluster: my-cluster
  namespace: streamsdemo
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
---
kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: temperature-values
  namespace: streamsdemo
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 3
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: temperatures-aggregated
  namespace: streamsdemo
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 3
  replicas: 3

